# Generated by Django 5.1.6 on 2025-03-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='private',
            field=models.BooleanField(default=False, verbose_name='私有'),
        ),
        migrations.AddField(
            model_name='topic',
            name='private',
            field=models.BooleanField(default=False, verbose_name='私有'),
        ),
    ]
