# Generated by Django 5.1.6 on 2025-03-01 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_private_topic_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
