# Generated by Django 5.1.6 on 2025-03-01 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry_share_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='share_token',
        ),
        migrations.AddField(
            model_name='entry',
            name='_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
