# Generated by Django 5.1.6 on 2025-03-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_remove_entry_share_token_entry__token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='_token',
            new_name='token',
        ),
    ]
